[package]
name = "dlt-bench"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dlt-bench"
path = "main.rs"

[dependencies]
dlt-user = { path = "../user" }
dlt-core = { path = "../core" }
clap = { version = "4.5", features = ["derive"] }
sysinfo = "0.30"
